import "./globals.css";

//Components
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Starter App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body>{children}</body>
    </html>
  );
}
