import "./globals.css";
import {Rubik} from 'next/font/google'

//Components
import Navbar from "./components/Navbar";

const rubik = Rubik({subsets: ['latin-ext']})

export const metadata = {
  title: "Starter App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
